# Generated by Django 4.2.6 on 2023-11-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_AppEtito', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('addressNumber', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend_AppEtito.user')),
            ],
        ),
    ]
