# Generated by Django 4.2.6 on 2023-11-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_AppEtito', '0003_alter_admin_password_alter_user_password_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='idUser',
            new_name='user',
        ),
    ]
