# Generated by Django 4.2.6 on 2023-11-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_AppEtito', '0005_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
