# Generated by Django 4.2.6 on 2023-11-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_AppEtito', '0007_restaurants_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='image',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='image',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to='photos/'),
        ),
    ]
