# Generated by Django 4.2.6 on 2023-11-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_AppEtito', '0008_foods_image_restaurants_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='image',
            field=models.ImageField(blank=True, default='path_to_default_image.jpg', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='image',
            field=models.ImageField(blank=True, default='path_to_default_image.jpg', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
