# Generated by Django 4.2.6 on 2023-11-15 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_AppEtito', '0009_alter_admin_photo_alter_categories_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend_AppEtito.locations')),
                ('paymentMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend_AppEtito.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend_AppEtito.user')),
            ],
        ),
    ]
